import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./UI/navBar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased w-[100vw] h-[100vh]`}
			>
				<section className="flex items-center justify-center">
					<nav className="w-[15vw] h-[95vh]">
						<NavBar />
					</nav>
					<main className="w-[85vw] h-[95vh]">
						<div className="flex items-center justify-center h-15 shrink-0 items-end rounded-lg bg-red-700 m-4 md:h-20">
							<img
								src="https://cdn.pixabay.com/photo/2016/08/06/08/05/pokemon-1574006_1280.png"
								alt="pika"
								className="h-[11vh] mr-4"
							/>
							Welcome to SAP !
						</div>
						{children}
					</main>
				</section>
				<footer className="w-[100vw] h-[5vh] flex items-center justify-center bg-red-700 rounded">
					<p>Created with love and crazyness</p>
				</footer>
			</body>
		</html>
	);
}
