import type { Metadata } from "next";
import { Mulish, Wallpoet } from "next/font/google";
import "./globals.css";
import NavBar from "./UI/navBar";

const mulish = Mulish({
	variable: "--font-mulish",
	subsets: ["latin"],
});
const wallpoet = Wallpoet({
	variable: "--font-wallpoet",
	subsets: ["latin"],
	weight: "400",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={
					"font-[family-name:var(--font-mulish)] antialiased w-[100vw] h-[100vh] bg-gray-950 text-white"
				}
			>
				<section className="flex items-center justify-center">
					<nav className="w-[15vw] h-[95vh]">
						<NavBar />
					</nav>
					<main className="w-[85vw] h-[97vh] md:h-[95vh]">
						<div className="flex items-center justify-center h-15 shrink-0 items-end rounded-lg bg-red-700 m-4 md:h-20">
							<img
								src="https://cdn.pixabay.com/photo/2016/08/06/08/05/pokemon-1574006_1280.png"
								alt="pika"
								className="h-[11vh] mr-4 text-xl"
							/>
							Welcome to SAP !
						</div>
						{children}
					</main>
				</section>
				<footer className="w-[100vw] h-[3vh] flex items-center justify-center bg-red-700 rounded md:h-[5vh]">
					<p>Created with love and crazyness</p>
				</footer>
			</body>
		</html>
	);
}
